name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Allow one instance of this workflow per pull request, and cancel older runs when new changes are pushed
concurrency:
  group: ci-yaml-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        # windows-latest does not work because of https://github.com/oli-obk/ui_test/issues/147
        os: [ubuntu-latest, macos-latest]
        java-version: ['17', '21']
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: ${{ matrix.java-version }}
    - name: Install mdBook
      if: matrix.os == 'ubuntu-latest'
      run: curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.28/mdbook-v0.4.28-x86_64-unknown-linux-gnu.tar.gz | tar -xz
    - name: Build
      run: cargo build --verbose
    - name: Test crates
      run: cargo test --all-targets --verbose
    - name: Test client crates
      run: cargo test --all-targets --verbose --manifest-path=test-crates/Cargo.toml
    - name: Test book
      if: matrix.os == 'ubuntu-latest'
      run: ./mdbook test book
